### ISSUE TITLE
gImageReader does not compile with 5.15.2

### ISSUE THREAD

**Issue by HJarausch** [manisandro/gImageReader#500]
With QT 5.15.2 I get

/var/tmp/portage/media-gfx/gimagereader-3.3.1/work/gimagereader-3.3.1/qt/src/hocr/HOCROdtExporter.cc: In member function 'bool HOCROdtExporter::run(const HOCRDocument*, QString&)':
/var/tmp/portage/media-gfx/gimagereader-3.3.1/work/gimagereader-3.3.1/qt/src/hocr/HOCROdtExporter.cc:261:35: error: incomplete type 'QUrl' used in nested name specifier
  261 |   QDesktopServices::openUrl(QUrl::fromLocalFile(outname));

Is there any fix?
Thanks,
Helmut

**Comment by pointer** [comment]
Hi,
add this #include <QUrl>
and modify like this:
		// QDesktopServices::openUrl(QUrl::fromLocalFile(outname));
		QUrl url = QUrl::fromLocalFile(outname);
		QDesktopServices::openUrl(url);

**Comment by HJarausch** [comment]
Many thanks **pointer**.  Now, all files compile but I get a lot of linkage errors which I don't understand:
```
Acquirer.cc:(.text+0x3): undefined reference to `vtable for Acquirer'
Config.cc:(.text+0x1d81): undefined reference to `vtable for Config'
```
and many more. Do you have an idea what's going wrong?

**Comment by manisandro** [comment]
You'll also want
https://github.com/manisandro/gImageReader/commit/197cf34eacb04fdb91845a50fe82326a16ccc9d2
and
https://github.com/manisandro/gImageReader/commit/e023778d9cd25d2d4065d51dbccc039d9aff44d1

**Comment by HJarausch** [comment]
Many thanks Sandro, it builds fine now on my Gentoo machine.
Helmut
